[package]
name = "i2-flappy_bird"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
olc_pixel_game_engine = "0.5.0"
rand = "0.6.5"
